### ISSUE TITLE
Optimize pulling movements from the Open Banking provider

### ISSUE THREAD

**Issue by EduardoSimon** [EduardoSimon/budget.io#29]
# Problem 
Currently, every single transaction is being retrieved from the past two months, even if it has already been registered in the database. 

# Idea
To enhance performance and responsiveness, an optimization can be implemented as follows:

- Retrieve the latest recorded transaction from the database.
- Dynamically request transactions from that point in time up to the present.

# Implementation notes:
There is a possibility of encountering phantom reads if multiple parallel jobs perform this operation simultaneously. However, for most scenarios, a simple read and write approach should be adequate.

**Comment by chahmedejaz** [comment]
Hey @EduardoSimon - I'd like to work on this issue, can you please assign it to me? Thanks. :)

**Comment by EduardoSimon** [comment]
Sure!

**Comment by chahmedejaz** [comment]
Hey @EduardoSimon - The fix for this issue has been submitted, would love to hear your thoughts on it. Thanks 😄 

**FYI:**
I opened the following issues while working on this one. Please validate these and label them as required.

- #36 
- #37 
- #38

**Comment by EduardoSimon** [comment]
Thank you for taking the time to create the issues, I have labelled them with the hacktoberfest label. I have assigned them to you, feel free to unassigned yourself from any of them.
