### ISSUE TITLE
Remove the Unused AuthSession Creation in the Seeds

### ISSUE THREAD

**Issue by chahmedejaz** [EduardoSimon/budget.io#38]
- I believe we should remove `AuthSession` creation from the `seeds.rb` because we are creating it with the dummy credentials and it fails to create it 
- Due to its failure, we are not creating the `Movement` data afterward.
- Moreover, I believe it's not being used in the `seeds.rb` as well, so no harm in removing it. After all, we are just creating the test data in the seeds.rb

**Comment by EduardoSimon** [comment]
That's a really interesting point, my idea was to create an account in the seed phase with a non-completed auth session leading the user to **authenticate** the account against the [mock institution](https://developer.gocardless.com/bank-account-data/sandbox) from gocardless, previously nordigen.

Another option is to completely ditch that approach and "mock" the usage of the open banking provider. 

So, how about if we:

 - Fix the creation of the auth session to leave it as a pending to be authenticated session but allowing to create movements anyway

**Comment by chahmedejaz** [comment]
> That's a really interesting point, my idea was to create an account in the seed phase with a non-completed auth session leading the user to **authenticate** the account against the [mock institution](https://developer.gocardless.com/bank-account-data/sandbox) from gocardless, previously nordigen.
> 
> Another option is to completely ditch that approach and "mock" the usage of the open banking provider.
> 
> So, how about if we:
> 
>     * Fix the creation of the auth session to leave it as a pending to be authenticated session but allowing to create movements anyway

Hey @EduardoSimon  -
Actually the main issue here is that we are using the dummy credentials to create the gocardless client:
https://github.com/EduardoSimon/budget.io/blob/160332e25f857464119ccb10f779cebff68ca6b3/.env#L1-L2
https://github.com/EduardoSimon/budget.io/blob/160332e25f857464119ccb10f779cebff68ca6b3/app/services/open_banking_connector.rb#L84-L87
- If we really need the AuthSession creation:
- We either need to use some valid credentials or mock the gocardless client
- I think for the proper validation of the changes, the developer must have the valid credentials for the gocardless client.
- I've some ideas of mocking the gocardless client, but for that we would need the responses schema for each of the endpoints we are using from the gocardless client.

Please let me know what do you think about it.

**Comment by chahmedejaz** [comment]
> We clearly need to document that a set an api key from GoCardless is needed. In fact, the app does nothing without it.
> 
> So how about documenting it? 

Yes, @EduardoSimon - we should implement this as part of the fix here. 
How about we apply the same approach,  writing the rake task to create AuthSession and skip the AuthSession creation in the seeds? 
We would document the rake tasks and their usage as well.

**Comment by EduardoSimon** [comment]
Awesome, let's go for it!
