### ISSUE TITLE
Add the new lint check step in the Makefile

### ISSUE THREAD

**Issue by chahmedejaz** [EduardoSimon/budget.io#45]
- It's observed that we are using the `bundle exec rake standard` in the GitHub workflows to check the linting issues.
- We need to update the `make lint` command respectively

**Comment by chahmedejaz** [comment]
Hey @EduardoSimon - Can you please label it accordingly and assign it to me? Thanks.

**Comment by chahmedejaz** [comment]
Hey @EduardoSimon - The fix for this issue has been submitted. Would love to hear your thoughts on it. :)

**Comment by EduardoSimon** [comment]
I do really appreaciate the time you are putting to the project, thank you very much! The PR seems great, let me merge it!

**Comment by chahmedejaz** [comment]
It's a pleasure working on this project 😄
